ScalaConsultants/zio-scala2-quickstart.g8

src/main/g8/src/main/scala/$package$/Boot.scala
- remove obsolete `ZIO.effect` and `flatten`
- remove double termination of Actor System (is now handled only by ZManaged)
- make Http binding/unbinding handled by ZManaged
=> cleanup Boot

src/main/g8/build.sbt
=> bump caliban version to 0.7.6

src/main/g8/src/main/resources/application.conf, src/main/g8/src/main/scala/$package$/api/Api.scala, src/main/g8/src/main/scala/$package$/api/graphql/$if(add_caliban_endpoint.truthy)$GraphQLApi.scala$endif$, src/main/g8/src/test/scala/$package$/api/ApiSpec.scala, src/main/g8/src/test/scala/$package$/api/graphql/$if(add_caliban_endpoint.truthy)$GraphQLApiSpec.scala$endif$
=> Add tests for GraphQLApi

src/main/g8/src/main/scala/$package$/Boot.scala, src/main/g8/src/main/scala/$package$/api/graphql/$if(add_caliban_endpoint.truthy)$GraphQLApi.scala$endif$, src/main/g8/src/main/scala/$package$/domain/DomainError.scala, src/main/g8/src/main/scala/$package$/domain/models.scala, src/main/g8/src/test/scala/$package$/api/graphql/$if(add_caliban_endpoint.truthy)$GraphQLApiSpec.scala$endif$
=> Remove dependency on Console for GraphQLApi

src/main/g8/build.sbt
Fix https://github.com/ScalaConsultants/zio-akka-quickstart.g8/issues/43
=> Update caliban to 0.7.7

src/main/g8/src/main/resources/application.conf
=> Add some explicit HikariCP configuration

src/main/g8/src/main/resources/logback.xml
=> Add logback configuration

README.markdown
=> Add note about ZLayer to readme

.github/workflows/scala.yml, src/main/g8/default.properties, src/main/g8/src/main/scala/$package$/api/Api.scala, src/main/g8/src/main/scala/$package$/application/ApplicationService.scala, src/main/g8/src/main/scala/$package$/domain/ItemRepository.scala, src/main/g8/src/main/scala/$package$/infrastructure/SlickItemRepository.scala, src/main/g8/src/test/scala/$package$/api/graphql/$if(add_caliban_endpoint.truthy)$GraphQLApiSpec.scala$endif$, src/main/g8/src/test/scala/$package$/domain/InMemoryItemRepository.scala
=> Add optional SSE endpoint

build.sbt, src/main/g8/build.sbt, src/main/g8/src/test/scala/$package$/api/graphql/$if(add_caliban_endpoint.truthy)$GraphQLApiSpec.scala$endif$
Fix #73.
graphql api was broken by this.
https://github.com/ghostdogpr/caliban/pull/430
=> Bump caliban and fix tests

src/main/g8/src/main/scala/$package$/domain/DomainError.scala, src/main/g8/src/main/scala/$package$/domain/models.scala
Hey guys. You forgot to template two of your files, leading to lots of compile errors.
=> Fix nontemplated package names

README.markdown, build.sbt, project/plugins.sbt, src/main/g8/build.sbt, src/main/g8/project/plugins.sbt, src/main/g8/src/main/scala/$package$/Boot.scala
=> Add docker packaging

build.sbt, src/main/g8/build.sbt, src/main/g8/src/test/scala/$package$/api/ApiSpec.scala, src/main/g8/src/test/scala/$package$/domain/InMemoryItemRepository.scala
=> Add WS and SSE endpoints tests

.github/workflows/scala.yml, project/plugins.sbt, src/main/g8/default.properties, src/main/g8/project/plugins.sbt, src/main/g8/src/main/scala/$package$/Boot.scala, src/main/g8/src/main/scala/$package$/api/Api.scala, src/main/g8/src/main/scala/$package$/api/graphql/$if(add_caliban_endpoint.truthy)$GraphQLApi.scala$endif$, src/main/g8/src/main/scala/$package$/api/protocol.scala, src/main/g8/src/main/scala/$package$/application/ApplicationService.scala, src/main/g8/src/main/scala/$package$/domain/ItemRepository.scala, src/main/g8/src/main/scala/$package$/infrastructure/SlickItemRepository.scala, src/main/g8/src/main/scala/$package$/infrastructure/tables/ItemsTable.scala, src/main/g8/src/test/scala/$package$/api/ApiSpec.scala, src/main/g8/src/test/scala/$package$/domain/InMemoryItemRepository.scala
1. Add optional plugin [sbt-tpolecat](https://github.com/DavidGregory084/sbt-tpolecat) (details in [Rob Norris (tpolecat) blog post](https://tpolecat.github.io/2017/04/25/scalac-flags.html)) to project/plugins.sbt. Add plugin [sbt-tpolecat](https://github.com/DavidGregory084/sbt-tpolecat) (details in [Rob Norris (tpolecat) blog post](https://tpolecat.github.io/2017/04/25/scalac-flags.html)) to project/plugins.sbt. Plugin added if user agree - flag `add_sbt_tpolecat`.
```scala
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.13")
```
2. and fix issues detected by this plugin:
* add explicit type to avoid resolving type to Any e.g. `def publishDeletedEvents(deletedItemId: ItemId): UIO[List[Boolean]]`
* add explicit tuple e.g. `logRequestResult(("sse/items", InfoLevel))`
* …
=> add sbt-tpolecat plugin for static analysis

build.sbt, src/main/g8/build.sbt, src/main/g8/src/main/scala/$package$/api/Api.scala
=> Updated ZIO to 1.0.0

.gitignore, .scalafmt.conf, build.sbt, src/main/g8/.gitignore, src/main/g8/build.sbt, src/main/g8/src/main/resources/db/migration/V1__Create_items_table.sql, src/main/g8/src/main/resources/db/migration/V2__Add_items.sql, src/main/g8/src/main/scala/$package$/Boot.scala, src/main/g8/src/main/scala/$package$/infrastructure/SlickItemRepository.scala, src/main/g8/src/main/scala/$package$/infrastructure/flyway/Flyway.scala, src/main/g8/src/main/scala/$package$/infrastructure/flyway/FlywayProvider.scala, src/main/g8/src/main/scala/$package$/infrastructure/flyway/MigrateResult.scala, src/main/g8/src/main/scala/$package$/infrastructure/flyway/package.scala, src/main/g8/src/main/scala/$package$/infrastructure/tables/ItemsTable.scala
Closes #152 
Tasks done:
* Fix .gitignore and build.sbt
* Refactor existing layers
* Remove schema creation from SlickItemRepository
* Integrate Flyway with ZIO
* Add auto-migration of DB schema at app startup
* Make package generic
* Fix build.sbt formatting
=> Allow the server to start without the database

build.sbt, src/main/g8/build.sbt
=> Update Caliban to 0.9.5

build.sbt, src/main/g8/README.md, src/main/g8/build.sbt, src/main/g8/default.properties, src/main/g8/src/main/scala/$package$/api/Api.scala, src/main/g8/src/main/scala/$package$/api/graphql/$if(add_caliban_endpoint.truthy)$GraphQLApi.scala$endif$, src/main/g8/src/main/scala/$package$/api/protocol.scala, src/main/g8/src/test/scala/$package$/api/ApiSpec.scala, src/main/g8/src/test/scala/$package$/api/graphql/$if(add_caliban_endpoint.truthy)$GraphQLApiSpec.scala$endif$
- zio-1.0.10 
- akka-http-10.2.6
- akka-2.6.15
- zio-rs-1.3.5
- caliban-1.1.1
- postgress-42.2.23
- flyway-7.12.1
- migrating play-json to zio-json
=> Update dependencies zio-akka-quickstart.g8

src/main/g8/src/main/scala/$package$/infrastructure/SlickHealthCheckService.scala
Fix slick.SlickException: Update statements should not return a ResultSet
=> Fix slick healthcheck

src/main/g8/src/main/resources/application.conf
at least in terms of what's indicated in the README re overwriting of certain defaults
> You can override the defaults with the following > environment variables:
> 
> - API_HOST
> - API_PORT
> - DB_HOST
> - DB_PORT
> - DB_NAME
> - DB_USER
> - DB_PASSWORD
=> resolve #135

src/main/g8/src/main/scala/$package$/api/$if(enable_akka_http.truthy)$ApiAkkaHttp.scala$endif$, src/main/g8/src/main/scala/$package$/api/$if(enable_zio_http.truthy)$ApiZioHttp.scala$endif$, src/main/g8/src/test/scala/$package$/api/$if(enable_akka_http.truthy)$ApiAkkaHttpSpec.scala$endif$
=> Improve responses for the post endpoint

src/main/g8/src/main/scala/$package$/api/$if(enable_akka_http.truthy)$ApiAkkaHttp.scala$endif$
=> fix: Use 404 http code for not found items

src/main/g8/src/main/scala/$package$/api/$if(enable_akka_http.truthy)$ApiAkkaHttp.scala$endif$, src/main/g8/src/main/scala/$package$/api/$if(enable_zio_http.truthy)$ApiZioHttp.scala$endif$, src/main/g8/src/main/scala/$package$/domain/DomainError.scala, src/main/g8/src/test/scala/$package$/api/$if(enable_akka_http.truthy)$ApiAkkaHttpSpec.scala$endif$
=> Fix inconsistent responses for delete endpoints

src/main/g8/src/main/scala/$package$/api/$if(enable_akka_http.truthy)$ApiAkkaHttp.scala$endif$, src/main/g8/src/main/scala/$package$/api/$if(enable_zio_http.truthy)$ApiZioHttp.scala$endif$, src/main/g8/src/main/scala/$package$/application/ApplicationService.scala
=> Fix inconsistent responses for put and patch endpoints

.github/workflows/scala.yml, build.sbt, project/build.properties, project/plugins.sbt, src/main/g8/build.sbt, src/main/g8/project/build.properties, src/main/g8/project/plugins.sbt
The goal here is to improve configuration files consistency between this and https://github.com/ScalaConsultants/zio-scala3-quickstart.g8 projects.
The counterpart to this is https://github.com/ScalaConsultants/zio-scala3-quickstart.g8/pull/107.
=> Improve build.sbt consistency
